#pragma once

#include "chess/move/piece_move.h"
#include "chess/move/piece_move_generator.h"

DEF_PATTERN_SET(PAWN,
    {N, 1, 1, SQUARE_EMPTY},
    {NE | NW, 1, 1, SQUARE_ENEMY},
    {N, 2, 1, SQUARE_EMPTY | PIECE_NEVER_MOVED},
    {NE | NW, 1, 1, SQUARE_EN_PASSANT, PIECE_MOVE_IS_EN_PASSANT}
);

DEF_PATTERN_SET(KNIGHT,
    {NNE | ENE | ESE | SSE | SSW | WSW | WNW | NNW, 1, 1, SQUARE_NOT_ALLY},
);

DEF_PATTERN_SET(BISHOP,
    {NE | SE | SW | NW, 1, -1, SQUARE_NOT_ALLY}
);

DEF_PATTERN_SET(ROOK, 
    {N | E | S | W, 1, -1, SQUARE_NOT_ALLY}
);

DEF_PATTERN_SET(QUEEN, 
    {N | NE | E | SE | S | SW | W | NW, 1, -1, SQUARE_NOT_ALLY}
);

DEF_PATTERN_SET(KING, 
    {N | NE | E | SE | S | SW | W | NW, 1, 1, SQUARE_NOT_ALLY, PIECE_MOVE_DISABLES_CASTLING_KING | PIECE_MOVE_DISABLES_CASTLING_QUEEN},
    {W, 2, 1, CASTLING_QUEEN_SIDE_ALLOWED | CASTLING_PATH_IS_CLEAR, PIECE_MOVE_IS_CASTLING | PIECE_MOVE_DISABLES_CASTLING_KING | PIECE_MOVE_DISABLES_CASTLING_QUEEN},
    {E, 2, 1, CASTLING_KING_SIDE_ALLOWED | CASTLING_PATH_IS_CLEAR, PIECE_MOVE_IS_CASTLING | PIECE_MOVE_DISABLES_CASTLING_KING | PIECE_MOVE_DISABLES_CASTLING_QUEEN}
);
