#pragma once

#include "chess/move/piece_move.h"
#include "chess/move/piece_move_generator.h"

DEF_PATTERN_SET(PAWN,
    {N, 1, 1, SQUARE_EMPTY, PIECE_MOVE_IS_NOT_REVERSIBLE},
    {NE | NW, 1, 1, SQUARE_ENEMY, PIECE_MOVE_IS_NOT_REVERSIBLE},
    {N, 2, 1, SQUARE_EMPTY | PIECE_NEVER_MOVED, PIECE_MOVE_IS_NOT_REVERSIBLE | PIECE_MOVE_ENABLES_ENPASSANT},
    {NE | NW, 1, 1, SQUARE_EN_PASSANT, PIECE_MOVE_IS_NOT_REVERSIBLE}
);

DEF_PATTERN_SET(KNIGHT,
    {NNE | ENE | ESE | SSE | SSW | WSW | WNW | NNW, 1, 1, SQUARE_NOT_ALLY},
);

DEF_PATTERN_SET(BISHOP,
    {NE | SE | SW | NW, 1, -1, SQUARE_NOT_ALLY}
);

DEF_PATTERN_SET(ROOK, 
    {N | E | S | W, 1, -1, SQUARE_NOT_ALLY}
);

DEF_PATTERN_SET(QUEEN, 
    {N | NE | E | SE | S | SW | W | NW, 1, -1, SQUARE_NOT_ALLY}
);

DEF_PATTERN_SET(KING, 
    {N | NE | E | SE | S | SW | W | NW, 1, 1, SQUARE_NOT_ALLY,
        PIECE_MOVE_DISABLES_CASTLING_KING | PIECE_MOVE_DISABLES_CASTLING_QUEEN}
);